### ISSUE TITLE
macOS  npm install blueimp-file-upload-expressjs  erro

### ISSUE THREAD

**Issue by doudouhe123** [arvindr21/blueimp-file-upload-expressjs#59]
when i install  blueimp-file-upload-expressjs, i found a mount  of erros,   I do not know how to fix it.

I was already install python 2.7 , xcode  Command Line Tools,  gcc and make all ok.

> lwip@0.0.6 install /Users/doudouhe/WebstormProjects/svn/aladdin_proj/trunk/cpc/node_modules/blueimp-file-upload-expressjs/node_modules/lwip
> node-gyp rebuild

2017-04-07 15:36:45.683 xcodebuild[64131:33653799] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMQuickHelp.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/lwip_decoder/src/decoder/init.o
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:120:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:115:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../../nan/nan.h:207:68: error: too many arguments to function call, expected at
      most 2, have 4
    return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
           ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:4832:3: note: 'New' declared
      here
  static Local<Signature> New(
  ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:262:32: warning: 'CompileUnbound' is deprecated
      [-Wdeprecated-declarations]
    return v8::ScriptCompiler::CompileUnbound(
                               ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:1334:45: note: 
      'CompileUnbound' has been explicitly marked deprecated here
                       Local<UnboundScript> CompileUnbound(
                                            ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:271:32: warning: 'CompileUnbound' is deprecated
      [-Wdeprecated-declarations]
    return v8::ScriptCompiler::CompileUnbound(
                               ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:1334:45: note: 
      'CompileUnbound' has been explicitly marked deprecated here
                       Local<UnboundScript> CompileUnbound(
                                            ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:277:31: warning: 'New' is deprecated [-Wdeprecated-declarations]
    return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                              ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:4007:56: note: 'New' has been
      explicitly marked deprecated here
  V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                       ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:289:3: error: redefinition of 'NanNew'
  NanNew<v8::StringObject, v8::Handle<v8::String> >(
  ^
../../nan/nan.h:282:3: note: previous definition is here
  NanNew<v8::StringObject, v8::Local<v8::String> >(
  ^
../../nan/nan.h:307:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:301:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:319:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:313:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::RegExp> NanNew(
                                   ^
../../nan/nan.h:327:42: warning: 'ToUint32' is deprecated
      [-Wdeprecated-declarations]
        v8::Isolate::GetCurrent(), val)->ToUint32();
                                         ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:8196:22: note: 'ToUint32' has
      been explicitly marked deprecated here
Local<Uint32> Value::ToUint32() const {
                     ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:333:42: warning: 'ToUint32' is deprecated
      [-Wdeprecated-declarations]
        v8::Isolate::GetCurrent(), val)->ToUint32();
                                         ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:8196:22: note: 'ToUint32' has
      been explicitly marked deprecated here
Local<Uint32> Value::ToUint32() const {
                     ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:338:60: warning: 'ToInt32' is deprecated
      [-Wdeprecated-declarations]
    return v8::Int32::New(v8::Isolate::GetCurrent(), val)->ToInt32();
                                                           ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:8202:21: note: 'ToInt32' has
      been explicitly marked deprecated here
Local<Int32> Value::ToInt32() const {
                    ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:343:60: warning: 'ToInt32' is deprecated
      [-Wdeprecated-declarations]
    return v8::Int32::New(v8::Isolate::GetCurrent(), val)->ToInt32();
                                                           ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:8202:21: note: 'ToInt32' has
      been explicitly marked deprecated here
Local<Int32> Value::ToInt32() const {
                    ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:388:24: warning: 'NewFromOneByte' is deprecated
      [-Wdeprecated-declarations]
    return v8::String::NewFromOneByte(
                       ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:2334:21: note: 
      'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:399:24: warning: 'NewFromOneByte' is deprecated
      [-Wdeprecated-declarations]
    return v8::String::NewFromOneByte(
                       ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:2334:21: note: 
      'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:408:24: warning: 'NewFromOneByte' is deprecated
      [-Wdeprecated-declarations]
    return v8::String::NewFromOneByte(v8::Isolate::GetCurrent(), arg);
                       ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:2334:21: note: 
      'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:414:24: warning: 'NewFromOneByte' is deprecated
      [-Wdeprecated-declarations]
    return v8::String::NewFromOneByte(v8::Isolate::GetCurrent(), arg);
                       ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:2334:21: note: 
      'NewFromOneByte' has been explicitly marked deprecated here
      Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                    ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:500:24: warning: 'NewExternal' is deprecated
      [-Wdeprecated-declarations]
    return v8::String::NewExternal(v8::Isolate::GetCurrent(), resource);
                       ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:2372:38: note: 'NewExternal'
      has been explicitly marked deprecated here
                       Local<String> NewExternal(
                                     ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:531:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:517:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:120:25: note: candidate template ignored: substitution failure
      [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:536:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::Null(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:517:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:120:25: note: candidate template ignored: substitution failure
      [with T = v8::Primitive]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:541:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:517:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:120:25: note: candidate template ignored: substitution failure
      [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:546:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(v8::False(v8::Isolate::GetCurrent())));
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:517:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:120:25: note: candidate template ignored: substitution failure
      [with T = v8::Boolean]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in
      'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in
      'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:778:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:789:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/doudouhe/.node-gyp/6.9.5/include/node/node_buffer.h:46:40: note: 
      candidate function not viable: 2nd argument ('const char *') would lose
      const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/node_buffer.h:34:40: note: 
      candidate function not viable: no known conversion from 'const char *' to
      'v8::Local<v8::String>' for 2nd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/node_buffer.h:31:40: note: 
      candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/node_buffer.h:39:40: note: 
      candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:793:12: error: no viable conversion from returned value of type
      'v8::MaybeLocal<v8::Object>' to function return type
      'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:218:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'const
      v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:218:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&'
      for 1st argument
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:222:13: note: candidate
      template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:800:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../../nan/nan.h:827:32: warning: 'Compile' is deprecated
      [-Wdeprecated-declarations]
    return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                               ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:1354:21: note: 'Compile' has
      been explicitly marked deprecated here
      Local<Script> Compile(Isolate* isolate, Source* source,
                    ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:834:32: warning: 'Compile' is deprecated
      [-Wdeprecated-declarations]
    return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                               ^
/Users/doudouhe/.node-gyp/6.9.5/include/node/v8.h:1354:21: note: 'Compile' has
      been explicitly marked deprecated here
      Local<Script> Compile(Isolate* isolate, Source* source,
                    ^
In file included from ../src/decoder/init.cpp:1:
In file included from ../src/decoder/decoder.h:13:
../../nan/nan.h:1897:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:517:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:120:25: note: candidate template ignored: substitution failure
      [with T = v8::Function]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:1912:12: error: no matching function for call to
      '_NanEnsureLocal'
    return NanEscapeScope(node::MakeCallback(
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../nan/nan.h:517:43: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                          ^~~~~~~~~~~~~~~
../../nan/nan.h:120:25: note: candidate template ignored: substitution failure
      [with T = v8::Value]
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
14 warnings and 20 errors generated.
make: *** [Release/obj.target/lwip_decoder/src/decoder/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/doudouhe/WebstormProjects/svn/aladdin_proj/trunk/cpc/node_modules/blueimp-file-upload-expressjs/node_modules/lwip
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
cpc@0.0.0 /Users/doudouhe/WebstormProjects/svn/aladdin_proj/trunk/cpc
└── (empty)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "blueimp-file-upload-expressjs" "--save"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! lwip@0.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lwip@0.0.6 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lwip package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lwip
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lwip
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doudouhe/WebstormProjects/svn/aladdin_proj/trunk/cpc/npm-debug.log
npm ERR! code 1

**Comment by zanderisrael** [comment]
Same Here

**Comment by GroomedGorilla** [comment]
Same issue here. There is no mention of pre-requisites for file installation in the doc or the errors. Has anyone had any luck with this?

**Comment by ldarren** [comment]
i had similar problem, and i have it fixed in my fork https://github.com/ldarren/blueimp-file-upload-expressjs

side note, in my fork the s3 upload is fully working with thumbnail
